### ISSUE TITLE
Sulu 2.0 Doc Tracking issue

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu-docs#447]
This is a list of all documentation sites. If somebody checked a documentation check the `checked` checkbox if its 2.0 compatible check also the link checkbox if work is needed let it empty.

- [x] [book/index.rst](http://docs.sulu.io/en/develop/book/index.html)
    - [x] checked
- [x] [book/admin-interface.rst](http://docs.sulu.io/en/develop/book/admin-interface.html)
    - [x] checked
    - [x] needs new screenshots
- [x] [book/content-architecture.rst](http://docs.sulu.io/en/develop/book/content-architecture.html)
    - [x] checked
- [x] [book/getting-started.rst](http://docs.sulu.io/en/develop/book/getting-started.html)
    - [x] checked
- [x] [book/image-formats.rst](http://docs.sulu.io/en/develop/book/image-formats.html)
    - [x] checked
    - [x] fixed paths
- [x] [book/localization.rst](http://docs.sulu.io/en/develop/book/localization.html)
    - [x] checked
- [x] [book/smart-content.rst](http://docs.sulu.io/en/develop/book/smart-content.html)
    - [x] checked
- [x] [book/templates.rst](http://docs.sulu.io/en/develop/book/templates.html)
    - [x] checked
    - [x] update content type list or link to content type reference page
    - [x] update screenshots
- [x] [book/themes.rst](http://docs.sulu.io/en/develop/book/themes.html)
    - [x] checked
    - [x] update config path
    - [x] add documentation to define a correct symfony 4 theme folder
- [x] [book/twig.rst](http://docs.sulu.io/en/develop/book/twig.html)
    - [x] checked
    - [x] use FCQN in controller path as bundle:test syntax is deprecated
    - [x] update screenshots
    - [x] add id parameter to other variables
- [x] [book/webspaces.rst](http://docs.sulu.io/en/develop/book/webspaces.html)
    - [x] checked
    - [x] update templates to use template path e.g. error/error-404
- [x] [book/introduction/index.rst](http://docs.sulu.io/en/develop/book/introduction/index.html)
    - [x] checked
- [x] [book/introduction/backend-template.rst](http://docs.sulu.io/en/develop/book/introduction/backend-template.html)
    - [x] checked
- [x] [book/introduction/components.rst](http://docs.sulu.io/en/develop/book/introduction/components.html)
    - [x] checked
- [x] [book/introduction/content-architecture.rst](http://docs.sulu.io/en/develop/book/introduction/content-architecture.html)
    - [x] checked
- [x] [book/introduction/content-management-platform.rst](http://docs.sulu.io/en/develop/book/introduction/content-management-platform.html)
    - [x] checked
- [x] [book/introduction/right-choice.rst](http://docs.sulu.io/en/develop/book/introduction/right-choice.html)
    - [x] checked
- [x] [book/introduction/structure.rst](http://docs.sulu.io/en/develop/book/introduction/structure.html)
    - [x] checked
- [x] [book/introduction/sulu-focus.rst](http://docs.sulu.io/en/develop/book/introduction/sulu-focus.html)
    - [x] checked
- [x] [bundles/index.rst](http://docs.sulu.io/en/develop/bundles/index.html)
    - [x] checked
- [x] [bundles/audience_targeting.rst](http://docs.sulu.io/en/develop/bundles/audience_targeting.html)
    - [x] checked
- [x] [bundles/collaboration.rst](http://docs.sulu.io/en/develop/bundles/collaboration.html)
    - [x] checked
    - [x] contains removed js code functionality
- [x] [bundles/hash.rst](http://docs.sulu.io/en/develop/bundles/hash.html)
    - [x] checked
- [x] [bundles/http_cache.rst](http://docs.sulu.io/en/develop/bundles/http_cache.html)
    - [x] checked
- [x] [bundles/media.rst](http://docs.sulu.io/en/develop/bundles/media.html)
    - [x] checked
- [x] [bundles/persistence.rst](http://docs.sulu.io/en/develop/bundles/persistence.html)
    - [x] checked
- [x] [bundles/search.rst](http://docs.sulu.io/en/develop/bundles/search.html)
    - [x] checked
- [x] [bundles/security.rst](http://docs.sulu.io/en/develop/bundles/security.html)
    - [x] checked
- [x] [bundles/admin/index.rst](http://docs.sulu.io/en/develop/bundles/admin/index.html)
    - [x] checked
- [x] [bundles/admin/ckeditor.rst](http://docs.sulu.io/en/develop/bundles/admin/ckeditor.html)
    - [x] checked
- [x] [bundles/admin/css.rst](http://docs.sulu.io/en/develop/bundles/admin/css.html)
    - [x] checked
- [x] [bundles/admin/sulu-buttons.rst](http://docs.sulu.io/en/develop/bundles/admin/sulu-buttons.html)
    - [x] checked
- [x] [bundles/admin/javascript-hooks/index.rst](http://docs.sulu.io/en/develop/bundles/admin/javascript-hooks/index.html)
    - [x] checked
- [x] [bundles/admin/javascript-hooks/collaboration.rst](http://docs.sulu.io/en/develop/bundles/admin/javascript-hooks/collaboration.html)
    - [x] checked
- [x] [bundles/admin/javascript-hooks/defaults.rst](http://docs.sulu.io/en/develop/bundles/admin/javascript-hooks/defaults.html)
    - [x] checked
- [x] [bundles/admin/javascript-hooks/events.rst](http://docs.sulu.io/en/develop/bundles/admin/javascript-hooks/events.html)
    - [x] checked
- [x] [bundles/admin/javascript-hooks/header.rst](http://docs.sulu.io/en/develop/bundles/admin/javascript-hooks/header.html)
    - [x] checked
- [x] [bundles/admin/javascript-hooks/layout.rst](http://docs.sulu.io/en/develop/bundles/admin/javascript-hooks/layout.html)
    - [x] checked
- [x] [bundles/admin/javascript-hooks/load-component-data.rst](http://docs.sulu.io/en/develop/bundles/admin/javascript-hooks/load-component-data.html)
    - [x] checked
- [x] [bundles/admin/javascript-hooks/sticky-toolbar.rst](http://docs.sulu.io/en/develop/bundles/admin/javascript-hooks/sticky-toolbar.html)
    - [x] checked
- [x] [bundles/automation/index.rst](http://docs.sulu.io/en/develop/bundles/automation/index.html)
    - [x] checked
- [x] [bundles/automation/handler.rst](http://docs.sulu.io/en/develop/bundles/automation/handler.html)
    - [x] checked
- [x] [bundles/automation/tab.rst](http://docs.sulu.io/en/develop/bundles/automation/tab.html)
    - [x] checked
- [x] [bundles/markup/index.rst](http://docs.sulu.io/en/develop/bundles/markup/index.html)
    - [x] checked
- [x] [bundles/markup/link.rst](http://docs.sulu.io/en/develop/bundles/markup/link.html)
    - [x] checked
- [x] [bundles/markup/media.rst](http://docs.sulu.io/en/develop/bundles/markup/media.html)
    - [x] checked
- [x] [bundles/page/index.rst](http://docs.sulu.io/en/develop/bundles/page/index.html)
    - [x] checked
- [x] [bundles/page/content-repository.rst](http://docs.sulu.io/en/develop/bundles/page/content-repository.html)
    - [x] checked
- [x] [bundles/page/drafting.rst](http://docs.sulu.io/en/develop/bundles/page/drafting.html)
    - [x] checked
- [x] [bundles/page/security.rst](http://docs.sulu.io/en/develop/bundles/page/security.html)
    - [x] checked
- [x] [bundles/page/versioning.rst](http://docs.sulu.io/en/develop/bundles/page/versioning.html)
    - [x] checked
- [x] [bundles/preview/index.rst](http://docs.sulu.io/en/develop/bundles/preview/index.html)
    - [x] checked
- [x] [bundles/route/index.rst](http://docs.sulu.io/en/develop/bundles/route/index.html)
    - [x] checked
- [x] [bundles/route/custom_route_generator.rst](http://docs.sulu.io/en/develop/bundles/route/custom_route_generator.html)
    - [x] checked
- [x] [bundles/website/index.rst](http://docs.sulu.io/en/develop/bundles/website/index.html)
    - [x] checked
- [x] [bundles/website/reference-store.rst](http://docs.sulu.io/en/develop/bundles/website/reference-store.html)
    - [x] checked
- [x] [cookbook/index.rst](http://docs.sulu.io/en/develop/cookbook/index.html)
    - [x] checked
- [x] [cookbook/caching-with-varnish.rst](http://docs.sulu.io/en/develop/cookbook/caching-with-varnish.html)
    - [x] checked
- [x] [cookbook/change-default-locale-provider.rst](http://docs.sulu.io/en/develop/cookbook/change-default-locale-provider.html)
    - [x] checked
- [x] [cookbook/create-new-webspace.rst](http://docs.sulu.io/en/develop/cookbook/create-new-webspace.html)
    - [x] checked
- [x] [cookbook/custom-error-page.rst](http://docs.sulu.io/en/develop/cookbook/custom-error-page.html)
    - [x] checked
- [x] [cookbook/custom-urls.rst](http://docs.sulu.io/en/develop/cookbook/custom-urls.html)
    - [x] checked
- [x] [cookbook/deactivate-request-analyzer.rst](http://docs.sulu.io/en/develop/cookbook/deactivate-request-analyzer.html)
    - [x] checked
- [x] [cookbook/default-snippets.rst](http://docs.sulu.io/en/develop/cookbook/default-snippets.html)
    - [x] checked
- [x] [cookbook/dump-sitemap.rst](http://docs.sulu.io/en/develop/cookbook/dump-sitemap.html)
    - [x] checked
- [x] [cookbook/enable-adobe-creative-suite.rst](http://docs.sulu.io/en/develop/cookbook/enable-adobe-creative-suite.html)
    - [x] checked
- [x] [cookbook/extend-entities.rst](http://docs.sulu.io/en/develop/cookbook/extend-entities.html)
    - [x] checked
- [x] [cookbook/external-media-storage.rst](http://docs.sulu.io/en/develop/cookbook/external-media-storage.html)
    - [x] checked
- [x] [cookbook/implement-entity-extensible.rst](http://docs.sulu.io/en/develop/cookbook/implement-entity-extensible.html)
    - [x] checked
- [x] [cookbook/integrating-custom-filters.rst](http://docs.sulu.io/en/develop/cookbook/integrating-custom-filters.html)
    - [x] checked
- [x] [cookbook/link-provider.rst](http://docs.sulu.io/en/develop/cookbook/link-provider.html)
    - [x] checked
- [x] [cookbook/localization-provider.rst](http://docs.sulu.io/en/develop/cookbook/localization-provider.html)
    - [x] checked
- [x] [cookbook/maintenance-mode.rst](http://docs.sulu.io/en/develop/cookbook/maintenance-mode.html)
    - [x] checked
- [x] [cookbook/manage-analytics.rst](http://docs.sulu.io/en/develop/cookbook/manage-analytics.html)
    - [x] checked
- [x] [cookbook/optimize-for-production-usage.rst](http://docs.sulu.io/en/develop/cookbook/optimize-for-production-usage.html)
    - [x] checked
- [x] [cookbook/override-dir-structure.rst](http://docs.sulu.io/en/develop/cookbook/override-dir-structure.html)
    - [x] checked
- [x] [cookbook/running-sulu-on-heroku.rst](http://docs.sulu.io/en/develop/cookbook/running-sulu-on-heroku.html)
    - [x] checked
- [x] [cookbook/securing-your-application.rst](http://docs.sulu.io/en/develop/cookbook/securing-your-application.html)
    - [x] checked
- [x] [cookbook/sitemap-provider.rst](http://docs.sulu.io/en/develop/cookbook/sitemap-provider.html)
    - [x] checked
- [x] [cookbook/smart-content-data-provider.rst](http://docs.sulu.io/en/develop/cookbook/smart-content-data-provider.html)
    - [x] checked
- [x] [cookbook/system-collections.rst](http://docs.sulu.io/en/develop/cookbook/system-collections.html)
    - [x] checked
- [x] [cookbook/use-request-analyzer-with-esi.rst](http://docs.sulu.io/en/develop/cookbook/use-request-analyzer-with-esi.html)
    - [x] checked
- [x] [cookbook/using-elasticsearch.rst](http://docs.sulu.io/en/develop/cookbook/using-elasticsearch.html)
    - [x] checked
- [x] [cookbook/using-tab-navigation.rst](http://docs.sulu.io/en/develop/cookbook/using-tab-navigation.html)
    - [x] checked
- [x] [cookbook/video-preview-images.rst](http://docs.sulu.io/en/develop/cookbook/video-preview-images.html)
    - [x] checked
- [x] [cookbook/web-server/index.rst](http://docs.sulu.io/en/develop/cookbook/web-server/index.html)
    - [x] checked
- [x] [cookbook/web-server/apache.rst](http://docs.sulu.io/en/develop/cookbook/web-server/apache.html)
    - [x] checked
- [x] [cookbook/web-server/built-in.rst](http://docs.sulu.io/en/develop/cookbook/web-server/built-in.html)
    - [x] checked
- [x] [cookbook/web-server/file-permissions.inc.rst](http://docs.sulu.io/en/develop/cookbook/web-server/file-permissions.inc.html)
    - [x] checked
- [x] [cookbook/web-server/nginx.rst](http://docs.sulu.io/en/develop/cookbook/web-server/nginx.html)
    - [x] checked
- [x] [developer/index.rst](http://docs.sulu.io/en/develop/developer/index.html)
    - [x] checked
- [x] [developer/bc-promise.rst](http://docs.sulu.io/en/develop/developer/bc-promise.html)
    - [x] checked
- [x] [developer/behat/context-reference.rst](http://docs.sulu.io/en/develop/developer/behat/context-reference.html)
    - [x] checked
- [x] [developer/behat/getting-started.rst](http://docs.sulu.io/en/develop/developer/behat/getting-started.html)
    - [x] checked
- [x] [developer/behat/index.rst](http://docs.sulu.io/en/develop/developer/behat/index.html)
    - [x] checked
- [x] [developer/contributing/index.rst](http://docs.sulu.io/en/develop/developer/contributing/index.html)
    - [x] checked
- [x] [developer/contributing/adding-translations.rst](http://docs.sulu.io/en/develop/developer/contributing/adding-translations.html)
    - [x] checked
- [x] [developer/contributing/pull-requests.rst](http://docs.sulu.io/en/develop/developer/contributing/pull-requests.html)
    - [x] checked
- [x] [developer/contributing/test-your-code.rst](http://docs.sulu.io/en/develop/developer/contributing/test-your-code.html)
    - [x] checked
- [x] [developer/create-bundle/index.rst](http://docs.sulu.io/en/develop/developer/create-bundle/index.html)
    - [x] checked
- [x] [developer/create-bundle/frontend-routing.rst](http://docs.sulu.io/en/develop/developer/create-bundle/frontend-routing.html)
    - [x] checked
- [x] [developer/create-bundle/frontend-structure.rst](http://docs.sulu.io/en/develop/developer/create-bundle/frontend-structure.html)
    - [x] checked
- [x] [developer/create-bundle/views-tabs.rst](http://docs.sulu.io/en/develop/developer/create-bundle/views-tabs.html)
    - [x] checked
- [x] [reference/index.rst](http://docs.sulu.io/en/develop/reference/index.html)
    - [x] checked
- [x] [reference/glossary.rst](http://docs.sulu.io/en/develop/reference/glossary.html)
    - [x] checked
- [x] [reference/requirements.rst](http://docs.sulu.io/en/develop/reference/requirements.html)
    - [x] checked
- [x] [reference/components/document-manager/index.rst](http://docs.sulu.io/en/develop/reference/components/document-manager/index.html)
    - [x] checked
- [x] [reference/components/document-manager/creating_documents.rst](http://docs.sulu.io/en/develop/reference/components/document-manager/creating_documents.html)
    - [x] checked
- [x] [reference/components/document-manager/debugging.rst](http://docs.sulu.io/en/develop/reference/components/document-manager/debugging.html)
    - [x] checked
- [x] [reference/components/document-manager/extending.rst](http://docs.sulu.io/en/develop/reference/components/document-manager/extending.html)
    - [x] checked
- [x] [reference/components/document-manager/fixtures.rst](http://docs.sulu.io/en/develop/reference/components/document-manager/fixtures.html)
    - [x] checked
- [x] [reference/components/document-manager/introduction.rst](http://docs.sulu.io/en/develop/reference/components/document-manager/introduction.html)
    - [x] checked
- [x] [reference/components/document-manager/subscribers.rst](http://docs.sulu.io/en/develop/reference/components/document-manager/subscribers.html)
    - [x] checked
- [x] [reference/components/document-manager/using_the_document_manager.rst](http://docs.sulu.io/en/develop/reference/components/document-manager/using_the_document_manager.html)
    - [x] checked
- [x] [reference/content-types/index.rst](http://docs.sulu.io/en/develop/reference/content-types/index.html)
    - [x] checked
- [x] [reference/content-types/block.rst](http://docs.sulu.io/en/develop/reference/content-types/block.html)
    - [x] checked
- [x] [reference/content-types/category_selection.rst](http://docs.sulu.io/en/develop/reference/content-types/category_selection.html)
    - [x] checked
- [x] [reference/content-types/checkbox.rst](http://docs.sulu.io/en/develop/reference/content-types/checkbox.html)
    - [x] checked
- [x] [reference/content-types/color.rst](http://docs.sulu.io/en/develop/reference/content-types/color.html)
    - [x] checked
- [x] [reference/content-types/contact_account_selection.rst](http://docs.sulu.io/en/develop/reference/content-types/contact_account_selection.html)
    - [x] checked
- [x] [reference/content-types/date.rst](http://docs.sulu.io/en/develop/reference/content-types/date.html)
    - [x] checked
- [x] [reference/content-types/email.rst](http://docs.sulu.io/en/develop/reference/content-types/email.html)
    - [x] checked
- [x] [reference/content-types/location.rst](http://docs.sulu.io/en/develop/reference/content-types/location.html)
    - [x] checked
- [x] [reference/content-types/media_selection.rst](http://docs.sulu.io/en/develop/reference/content-types/media_selection.html)
    - [x] checked
- [x] [reference/content-types/page_selection.rst](http://docs.sulu.io/en/develop/reference/content-types/page_selection.html)
    - [x] checked
- [x] [reference/content-types/password.rst](http://docs.sulu.io/en/develop/reference/content-types/password.html)
    - [x] checked
- [x] [reference/content-types/phone.rst](http://docs.sulu.io/en/develop/reference/content-types/phone.html)
    - [x] checked
- [x] [reference/content-types/resource_locator.rst](http://docs.sulu.io/en/develop/reference/content-types/resource_locator.html)
    - [x] checked
- [x] [reference/content-types/select.rst](http://docs.sulu.io/en/develop/reference/content-types/select.html)
    - [x] checked
- [x] [reference/content-types/single_account_selection.rst](http://docs.sulu.io/en/develop/reference/content-types/single_account_selection.html)
    - [x] checked
- [x] [reference/content-types/single_contact_selection.rst](http://docs.sulu.io/en/develop/reference/content-types/single_contact_selection.html)
    - [x] checked
- [x] [reference/content-types/single_media_selection.rst](http://docs.sulu.io/en/develop/reference/content-types/single_media_selection.html)
    - [x] checked
- [x] [reference/content-types/single_page_selection.rst](http://docs.sulu.io/en/develop/reference/content-types/single_page_selection.html)
    - [x] checked
- [x] [reference/content-types/single_select.rst](http://docs.sulu.io/en/develop/reference/content-types/single_select.html)
    - [x] checked
- [x] [reference/content-types/smart_content.rst](http://docs.sulu.io/en/develop/reference/content-types/smart_content.html)
    - [x] checked
- [x] [reference/content-types/snippet_selection.rst](http://docs.sulu.io/en/develop/reference/content-types/snippet_selection.html)
    - [x] checked
- [x] [reference/content-types/tag_selection.rst](http://docs.sulu.io/en/develop/reference/content-types/tag_selection.html)
    - [x] checked
- [x] [reference/content-types/teaser_selection.rst](http://docs.sulu.io/en/develop/reference/content-types/teaser_selection.html)
    - [x] checked
- [x] [reference/content-types/text_area.rst](http://docs.sulu.io/en/develop/reference/content-types/text_area.html)
    - [x] checked
- [x] [reference/content-types/text_editor.rst](http://docs.sulu.io/en/develop/reference/content-types/text_editor.html)
    - [x] checked
- [x] [reference/content-types/text_line.rst](http://docs.sulu.io/en/develop/reference/content-types/text_line.html)
    - [x] checked
- [x] [reference/content-types/time.rst](http://docs.sulu.io/en/develop/reference/content-types/time.html)
    - [x] checked
- [x] [reference/content-types/url.rst](http://docs.sulu.io/en/develop/reference/content-types/url.html)
    - [x] checked
- [ ] [reference/twig-extensions/index.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/index.html)
    - [ ] checked
- [x] [reference/twig-extensions/filters/sulu_util_multisort.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/filters/sulu_util_multisort.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/_navigation_structure.inc](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/_navigation_structure.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/_page_structure.inc](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/_page_structure.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/_snippet_structure.inc](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/_snippet_structure.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_breadcrumb.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_breadcrumb.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_categories.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_categories.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_category_url.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_category_url.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_category_url_append.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_category_url_append.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_category_url_clear.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_category_url_clear.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_content_load.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_content_load.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_content_load_parent.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_content_load_parent.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_content_path.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_content_path.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_content_root_path.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_content_root_path.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_get_media_url.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_get_media_url.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_meta_alternate.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_meta_alternate.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_meta_seo.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_meta_seo.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_navigation_flat.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_navigation_flat.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_navigation_root_flat.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_navigation_root_flat.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_navigation_root_tree.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_navigation_root_tree.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_navigation_tree.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_navigation_tree.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_resolve_contact.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_resolve_contact.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_resolve_media.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_resolve_media.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_resolve_medias.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_resolve_medias.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_resolve_user.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_resolve_user.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_seo.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_seo.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_sitemap.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_sitemap.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_sitemap_url.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_sitemap_url.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_snippet_load.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_snippet_load.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_snippet_load_by_area.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_snippet_load_by_area.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_snippet_load_default.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_snippet_load_default.html)
    - [x] checked
    - [x] Remove because it is deprecated?
- [x] [reference/twig-extensions/functions/sulu_tag_url.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_tag_url.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_tag_url_append.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_tag_url_append.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_tag_url_clear.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_tag_url_clear.html)
    - [x] checked
- [x] [reference/twig-extensions/functions/sulu_tags.rst](http://docs.sulu.io/en/develop/reference/twig-extensions/functions/sulu_tags.html)
    - [x] checked
